package com.example.paritosh.ldh;

import android.content.Intent;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import java.lang.reflect.Array;

public class transportCarrier extends AppCompatActivity {
    ListView transport;
    String [] nameoftransport = new  String[]
            {
                    "A Complete Logistics Solution New Kuldip Goods Carrier (Regd.)",
                    "Aarti International Packers And Movers",
                    "A. S. Roadlines",
                    "ABC Packers And Movers",
                    "ABHISHEK Transport Corporation",
                    "AITC All India Transport Carriers",
                    "AITS All India Trailer Syndicate",
                    "AMIT CARGO ( INDIA )",
                    "ATO AJAY TRANSPORT ORGANISATION",
                    "ALL INDIA PACKERS AND MOVERS",
                    "ALWAR LUDHIANA ROADWAYS",
                    "ALWAR TRANSPORT SERVICE",
                    "AMERICAN Transport Corporation",
                    "ANKUR CARRIER",
                    "APS Parcel Carriers ( Regd. )",
                    "ASHOKA ROADWAYS CORPORATION",
                    "A-WON CARGO MOVERS",
                    "AYUSH TRAILER SERVICE",
                    "BAJAJ Freight Carriers",
                    "BALAJI FREIGHT CARRIER",
                    "BALAJI GOLDEN TRANSPORT CO.",
                    "RPS Express Cargo",
                    "BANDAH BAHADUR CARGO CARRIER",
                    "BARNALA GUJRAT CARRIER",
                    "BEST LOGISTIC SOLUTIONS",
                    "BEST ROADWAYS LIMITED",
                    "BGFC MOVERS ( INDIA ) Pvt. Ltd.",
                    "BHARAT GOURAV FREIGHT CARRIERS",
                    "BHARAT ROAD CARRIERS",
                    "BHARDWAJ Cargo Movers",
                    "BIHAR BENGAL CARGO CARRIERS",
                    "BILLING ROADLINES",
                    "BLR LOGISTIKS ( I ) LTD.",
                    "BOMBAY CARRIERS",
                    "BOMBAY CHANDIGARH ROAD CARRIERS",
                    "BOMBAY GOLDEN TRANSPORT Co. ( Regd. )",
                    "BROTHER TRANSPORT COMPANY",
                    "BRUNT ROADLINES OF INDIA",
                    "CARAVAN ROADWAYS LIMITED",
                    "CARAVAN TRANSPORT ORG. ( INDIA )",
                    "CHANDIGARH RAIPUR TRANSPORT",
                    "D.S. Transport Corporation ( Regd. )",
                    "CONTINENTAL CARRIERS Pvt. Ltd.",
                    "DAMAN CONTAINER SERVICE",
                    "DASMESH GOODS CARRIER PVT. LTD.",
                    "DASHMESH DARVESH",
                    "DELHI AMRITSAR ROADLINES",
                    "DELHI ASANSOL TRANSPORT CO.",
                    "DELHI BOMBAY LOGISTICS",
                    "DELHI LUDHIANA Transport Service ( Regd. )",
                    "DELHI LUDHIANA Transport Service",
                    "DELHI RAJASTHAN TRANSPORT Co. Ltd.",
                    "DELHI ROAD CARRIER",
                    "DELHI UP MP TRANSPORT CO. ( REGD. )",
                    "DELUXE TRANSPORT CO",
                    "DPR Cargo Express Road Service",
                    "DRS Transport Company",
                    "DHILLON CRANE SERVICE",
                    "DUTT ROADLINE",
                    "FRONTIER ROADLINES INDIA ( REGD. )",
                    "G.R. Roadways Corporation",
                    "GAGANDEEP ROADLINES",
                    "GALE BESTWAYS",
                    "GANESH ROADLINES",
                    "GARCHA FREIGHT CARRIERS",
                    "GHUMAN TEMPU UNION",
                    "GILL ROADWAYS",
                    "GLOBE INTERNATIONAL CARRIERS Pvt. Ltd.",
                    "GLOBE ROADWAYS",
                    "GLOBE TRANSPORT CORPORATION",
                    "GLOBE TRANSPORT SERVICE ( PUNJAB )",
                    "GOVIND TRANSPORT CORPORATION (REGD.)",
                    "GREEN CARRIERS & CONTRACTORS(DELHI) Pvt. Ltd.",
                    "GREWAL GOODS CARRIER",
                    "GREWAL ROAD CARRIER",
                    "G.S. KANG TRAILER SERVICE",
                    "GREWAL TRAILOR SERVICE",
                    "GREWAL TRANSPORT CO.",
                    "GREWAL LOGISTICS",
                    "GUJRAT RAJASTHAN ROADLINES",
                    "GURINDER SINGH CRANE & TRAILER SERVICE",
                    "GURMUKH TRANSPORT SERVICE",
                    "GURU NANAK CRANE",
                    "GURU NANAK TEMPO TRANSPORT SERVICE",
                    "GURU NANAK TRANSPORT COMPANY",
                    "GURU NANAK TRANSPORT COMPANY",
                    "HARGOBIND ROADLINES",
                    "HARIMANDER TRANSPORT GOODS CARRIERS",
                    "HARINDER ROADLINES",
                    "HARYANA Golden Transport.",
                    "HARYANA Golden Transport Co.",
                    "HARYANA NASHIK FREIGHT CARRIER",
                    "Hindustan Motor Transoprt Co. of India",
                    "HUNDAL CRANE SERVICE",
                    "INDIAN CARGO Transport Co.",
                    "IQBAL ROAD CARRIER",
                    "J.B. Transport Co. (Regd.)",
                    "J K FREIGHT CARRIER",
                    "J & K LOGISTICS",
                    "J. R. CARGO MOVERS",
                    "J. S. ROADWAYS",
                    "JAI BHARAT ROAD CARRIERS",
                    "JAI BHAWANI CARGO CARRIERS",
                    "JAI DURGE GOODS CARRIERS",
                    "JAI HIND TRANSPORT Corp.",
                    "JAI MAA SANTOSHI ROADLINES",
                    "JAI MAHARASHTRA Cargo Movers",
                    "JAI PUNJAB GOODS CARRIER",
                    "JAI SHREE Roadlines.",
                    "Jangra Freight Carrier",
                    "JASPREET GOODS CARRIER",
                    "JBR CARRIERS",
                    "JEET EXPRESS CARGO",
                    "JK FREIGHT CARRIER",
                    "JAMMU DELHI TRANSPORT COMPANY",
                    "JYOTI ROAD LINE",
                    "KARAN CARGO MOVERS",
                    "KARTAR CARRIERS (P) Ltd.",
                    "Kartik Ganpati Logistics",
                    "KATARIA TEMPO TRANSPORT SERVICE",
                    "KESAR CARGO MOVERS",
                    "KEWAL CARGO CARRIERS Pvt. Ltd.",
                    "KHANDA ROADWAYS CO. ( REGD. )",
                    "KHERA TRAILER SERVICE",
                    "KHUSHDIL ROADWAYS LDH. ( REGD. )",
                    "KRISHNA CARGO CARRIERS",
                    "KRISHNA FREIGHT MOVERS ( REGD. )",
                    "KRISHNA RAMA LOGISTICS",
                    "LEO INTERNATIONAL PACKERS & MOVERS",
                    "LINK ROADWAYS",
                    "LUDHIANA AMRITSAR ROAD CARRIERS",
                    "LUDHIANA CARGO MOVERS",
                    "LUDHIANA MADHYA PRADESH ROADWAYS",
                    "LUDHIANA SILIGURI ROAD CARRIERS",
                    "LUDHIANA SONEPAT CARRIER",
                    "LUDHIANA TRAILER SERVICE (REGD.)",
                    "MAA CHINTPURNI ROADLINES",
                    "MAHABIR TRANSPORT CO.",
                    "MAHADEV LOGISTICS (INDIA)",
                    "MAHARASHTRA GUJRAT ROADLINES",
                    "MALWA GOLDEN TRANSPORT CO.",
                    "MALWA TRANSPORT CO.",
                    "MANDAWAR MAHUWA CARGO MOVERS",
                    "MANGAT Trailer Syndicate",
                    "MILAP TRANSPORT COMPANY",
                    "MITTAL ROAD CARRIERS",
                    "Moga Road Service & Transport Co.",
                    "MOJI ROADLINES",
                    "MONDAIR GOLDEN CARRIER",
                    "MOONLIGHT TRANSPORT COMPANY",
                    "MOONLIGHT FREIGHT CARRIERS",
                    "MORINDA ROAD CARRIER",
                    "M.P. CHHATTISGARH ROADLINES",
                    "N.P.C. Transport Union ( Regd. )",
                    "N.R. CARGO MOVERS ( Regd. )",
                    "NANKANA SAHIB ROADLINES",
                    "NATIONAL ROAD CARRIERS ( Regd. )",
                    "NAVDEEP GOODS CARRIER",
                    "NAVDEEP ROAD CARRIERS",
                    "NAVDURGA ROAD CARRIERS",
                    "NAVKAR GOODS CARRIERS",
                    "NEHA ROAD CARRIER",
                    "NEW AKAL GOODS CARRIER",
                    "NEW AMRITSAR PATNA ROADWAYS",
                    "NEW CALCATTA MOTOR TRANSPORT",
                    "NEW DELHI MP ROADLINE",
                    "NEW CALCATTA ROADWAYS",
                    "NEW GLOBE ROADWAYS",
                    "NEW GREENLAND TRANSPORT CO. Regd.",
                    "NEW GREWAL TRANSPORT CO.",
                    "NEW HARYANA GOLDEN TRANSPORT Co.",
                    "NEW J.K. Transport Co.",
                    "NEW JANTA ROAD TRANSPORT CO. ( Regd. )",
                    "NEW KAMAL GOODS FREIGHT CARRIER",
                    "NEW KAMAL TRANSPORT",
                    "NEW LUDHIANA PANIPAT TRANSPORT CO.",
                    "NEW MOGA LOGISTICS",
                    "NEW POPULAR GOODS TRANSPORT COMPANY",
                    "NEW UP PUNJAB GOODS CARRIER",
                    "NEW South Leo Packers And Movers.",
                    "New THANDI TRANSPORT SERVICE",
                    "NISHTHA Roadlines",
                    "NORTH WEST ROADLINES Pvt. Ltd.",
                    "Om Shiv Shaskti Transport Co.",
                    "ORISSA GOODS CARRIER",
                    "PAL FREIGHT CARRIERS Pvt. Ltd.",
                    "PANJRATH ROAD CARRIERS",
                    "PANKAJ Freight Carriers",
                    "PANESAR TRANSPORT CO.",
                    "PARAS TRANSPORT CO.",
                    "PARAMOUNT CARRIERS ( REGD.)",
                    "PARTAP GOODS CARRIERS",
                    "PAWAN GOODS CARRIERS",
                    "PAWAN GOODS CARRIERS",
                    "PERFECT ROADLINES",
                    "PINKY ROADLINES",
                    "Piyush International Packers & Movers",
                    "PRAGATI LOGISTICS ( INDIA )",
                    "PRAKASH ROADLINES Ltd.",
                    "PREET CONTAINER SERVICE",
                    "PREET TEMPO TRANSPORT SERVICE",
                    "PREET TRANSPORT Co.",
                    "PREMIER CRANES & TRAILOR SERVICE",
                    "PUNJAB ANDHRA ROADLINES",
                    "PUNJAB BENGAL ROADLINES",
                    "PUNJAB CONTAINER SERVICE",
                    "PUNJAB ORISSA GOODS CARRIERS",
                    "PUNJAB RAJASTHAN TEMPO TRANSPORT SERVICE",
                    "R.C.I. - Rajdhani Corporation India",
                    "R.C.I. - Roadlines Corporation India",
                    "R.S. CARGO EXPRESS",
                    "RAI ROADLINES",
                    "RAJASTHAN Haryana Tempo Service",
                    "RAGHUBINDRA ROAD CARRIER",
                    "RAJASTHAN Roadways Corporation",
                    "RAJDHANI CARRING CORPORATION (PUNJAB)",
                    "RAJIV ROADLINES",
                    "RAJKOT GOLDEN GOODS CARRIER PVT. LTD.",
                    "RAJKOT GOLDEN LOGISTICS PVT. LTD.",
                    "RANA FREIGHT CARRIERS",
                    "RAMAN LOGISTIC",
                    "RANDHAWA TRAILER CARRIER",
                    "RANJEET CARRIERS",
                    "RASHTRIYA TRANSPORT CARGO (REGD.)",
                    "RAVI FREIGHT CARRIERS",
                    "RAVI ROADWAYS ( INDIA )",
                    "RISHAB CONTAINER SERVICE",
                    "ROAD TRANSPORT ORGANISATION ( Regd.)",
                    "ROADWAYS INDIA LIMITED",
                    "ROHIT CARGO MOVERS PVT. LTD.",
                    "ROPAR DELHI ROADLINE ( REGD. )",
                    "ROPAR LUDHIANA TRANSPORT CO.",
                    "S. S. ROADWAYS",
                    "SACHDEVA FREIGHT CARRIERS",
                    "SACHIN ROADLINES PRIVATE LIMITED",
                    "SAGAR Rorad Carriers",
                    "SAINI CARGO MOVERS",
                    "SAMPARK LOGISTICS Pvt. Ltd.",
                    "SAMRA GOODS CARRIER",
                    "SAMRA TRANSPORT TRADERS",
                    "SANGHU TRANSPORT COMPANY",
                    "SANJAY ROADLINES",
                    "SATGURU TEMPO TRANSPORT SERVICE",
                    "SATKAR LOGISTICS PVT. LTD.",
                    "SATKAR ROADLINES",
                    "SATNAM ROADWAYS ( REGD. )",
                    "SATYAM Road Carriers",
                    "SHAHI TRANSPORT SERVICE",
                    "SHERE PUNJAB CONTAINERS SERVICE",
                    "SHIV GANGA Transport Co",
                    "SHIV ROAD CARRIERS OF INDIA",
                    "SHIVA LOGISTICS",
                    "SHIVA OIL CARRIERS",
                    "SHIVAM ROADLINE INDIA (REGD.)",
                    "SHREE BISHNU CARRIERS",
                    "SHREE INDIA LOGISTICS",
                    "SHREE KRISHNA LOGISTICS",
                    "SHREE KRISHNA LOGISTICS ( INDIA )",
                    "SHREE RAJ CARRYING CORP.",
                    "SHREE RAM MOTOR TRANSPORT COMPANY",
                    "SHREE KRISHNA ROAD SERVICE",
                    "SHREE ROAD CARRIERS",
                    "SHREE S.K. ROADLINES",
                    "SHREE SHIV SHAKTI LOGISTICS",
                    "SHRI BALAJI LOGISTIC",
                    "SHRI BALAJI ROADWAYS ( I ) LIMITED.",
                    "SHRI GANESH TRANSPORT COMPANY",
                    "SHRI RAM CARGO MOVERS ( Regd. )",
                    "SHRINIWASA ROADWAYS Pvt. Ltd.",
                    "SIDH SHIVA CARGO MOVERS",
                    "SIMRAN ROAD CARRIERS",
                    "SINGLA ROADLINES",
                    "SITCO LOGISTICS ( INDIA )",
                    "SIWATCH TRANSPORT CO",
                    "SRC Logistics",
                    "SRI KRISHNA CARGO MOVERS",
                    "SRI WAHEGURU TRANSPORT COMPANY",
                    "SUNITAL GOLDEN TRANSPORT CO.",
                    "SUPER LOGISTICS ( LUDHIANA )",
                    "SURAB BOMBAY ROAD CARRIER",
                    "SOUTH INDIAN PACKERS & MOVERS",
                    "SOUTH LEO PACKERS & MOVERS OF INDIA",
                    "SUKHAM PACKERS AND MOVERS",
                    "SUKHAM GOODS BOOKING AGENCY LUDHIANA",
                    "SUPREME VAHAN CARGO MOVERS",
                    "TARUN LOGISTICS",
                    "THE JANTA TRANSPORT CORPORATION",
                    "THE PUNJAB TRANSPORT CARRIERS ( Regd. )",
                    "TIMES LOGISTICS LIMITED",
                    "TIRUPATI BALAJI TRANSPORT",
                    "TNR Roadways",
                    "UNIVERSAL CONTAINER SERVICE",
                    "VIKAS TRANSPORT COMPANY",
                    "VIKRANT ROAD LINES",
                    "VISHNU ROADLINES & TEMPO SERVICE",
                    "VIRK ROAD CARRIER",
                    "VISHWAHIND LOGISTICS LIMITED",
                    "VIVEKA Logistics Solutions Pvt. Ltd.",
                    "WALIA TRANSPORT CO."
            };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
            setTitle("TRANSPORT CARRIERS");
        setContentView(R.layout.activity_transport_carrier);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        transport=(ListView)findViewById(R.id.transport);
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,android.R.id.text1,nameoftransport);
        transport.setAdapter(adapter);

        transport.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Intent it = new Intent(transportCarrier.this,transportCarrierFinal.class);
                it.putExtra("POSITION",position);
                    it.putExtra("name",nameoftransport[position]);
                startActivity(it);
            }
        });

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });
    }

}
